// Les 48 nations qualifiées pour la Coupe du Monde 2026.
// Noms IDENTIQUES à ceux renvoyés par The Odds API (et stockés dans `matches`),
// pour rester cohérent avec l'affichage des matchs et permettre le matching
// du prono "vainqueur du tournoi". code = code flagcdn.
export const NATIONS = [
  { name: 'Algeria', code: 'dz' },
  { name: 'Argentina', code: 'ar' },
  { name: 'Australia', code: 'au' },
  { name: 'Austria', code: 'at' },
  { name: 'Belgium', code: 'be' },
  { name: 'Bosnia & Herzegovina', code: 'ba' },
  { name: 'Brazil', code: 'br' },
  { name: 'Canada', code: 'ca' },
  { name: 'Cape Verde', code: 'cv' },
  { name: 'Colombia', code: 'co' },
  { name: 'Croatia', code: 'hr' },
  { name: 'Curaçao', code: 'cw' },
  { name: 'Czech Republic', code: 'cz' },
  { name: 'DR Congo', code: 'cd' },
  { name: 'Ecuador', code: 'ec' },
  { name: 'Egypt', code: 'eg' },
  { name: 'England', code: 'gb-eng' },
  { name: 'France', code: 'fr' },
  { name: 'Germany', code: 'de' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Iran', code: 'ir' },
  { name: 'Iraq', code: 'iq' },
  { name: 'Ivory Coast', code: 'ci' },
  { name: 'Japan', code: 'jp' },
  { name: 'Jordan', code: 'jo' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Morocco', code: 'ma' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'New Zealand', code: 'nz' },
  { name: 'Norway', code: 'no' },
  { name: 'Panama', code: 'pa' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Scotland', code: 'gb-sct' },
  { name: 'Senegal', code: 'sn' },
  { name: 'South Africa', code: 'za' },
  { name: 'South Korea', code: 'kr' },
  { name: 'Spain', code: 'es' },
  { name: 'Sweden', code: 'se' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Tunisia', code: 'tn' },
  { name: 'Turkey', code: 'tr' },
  { name: 'Uruguay', code: 'uy' },
  { name: 'USA', code: 'us' },
  { name: 'Uzbekistan', code: 'uz' },
]

export const flagUrl = (code, size = 'w40') =>
  code ? `https://flagcdn.com/${size}/${code}.png` : ''
