// 48 nations qualifiées / candidates pour la Coupe du Monde 2026.
// code = code flagcdn (ISO 3166-1 alpha-2, ou variantes UK).
export const NATIONS = [
  { name: 'Argentine', code: 'ar' },
  { name: 'France', code: 'fr' },
  { name: 'Brésil', code: 'br' },
  { name: 'Angleterre', code: 'gb-eng' },
  { name: 'Espagne', code: 'es' },
  { name: 'Allemagne', code: 'de' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Pays-Bas', code: 'nl' },
  { name: 'Belgique', code: 'be' },
  { name: 'Croatie', code: 'hr' },
  { name: 'Italie', code: 'it' },
  { name: 'Uruguay', code: 'uy' },
  { name: 'Maroc', code: 'ma' },
  { name: 'États-Unis', code: 'us' },
  { name: 'Mexique', code: 'mx' },
  { name: 'Canada', code: 'ca' },
  { name: 'Japon', code: 'jp' },
  { name: 'Corée du Sud', code: 'kr' },
  { name: 'Sénégal', code: 'sn' },
  { name: 'Suisse', code: 'ch' },
  { name: 'Danemark', code: 'dk' },
  { name: 'Pologne', code: 'pl' },
  { name: 'Serbie', code: 'rs' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Cameroun', code: 'cm' },
  { name: 'Équateur', code: 'ec' },
  { name: 'Arabie Saoudite', code: 'sa' },
  { name: 'Australie', code: 'au' },
  { name: 'Tunisie', code: 'tn' },
  { name: 'Iran', code: 'ir' },
  { name: 'Colombie', code: 'co' },
  { name: 'Nigéria', code: 'ng' },
  { name: 'Égypte', code: 'eg' },
  { name: 'Algérie', code: 'dz' },
  { name: "Côte d'Ivoire", code: 'ci' },
  { name: 'Ukraine', code: 'ua' },
  { name: 'Autriche', code: 'at' },
  { name: 'Pays de Galles', code: 'gb-wls' },
  { name: 'Écosse', code: 'gb-sct' },
  { name: 'Norvège', code: 'no' },
  { name: 'Suède', code: 'se' },
  { name: 'Turquie', code: 'tr' },
  { name: 'Pérou', code: 'pe' },
  { name: 'Chili', code: 'cl' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Costa Rica', code: 'cr' },
  { name: 'Panama', code: 'pa' },
  { name: 'Nouvelle-Zélande', code: 'nz' },
]

export const flagUrl = (code, size = 'w40') =>
  code ? `https://flagcdn.com/${size}/${code}.png` : ''
